apiVersion: apps/v1
kind: Deployment
metadata:
  name: linux
spec:
  selector:
    matchLabels:
      app: linux
  replicas: 1 # tells deployment to run 2 pods matching the template
  template:
    metadata:
      labels:
        app: linux
    spec:
      containers:
      - name: nginx
        image: nginx:1.23.3-alpine
        ports:
        - containerPort: 80
        resources:
          limits:
            cpu: 1000m 
            memory: 256Mi
          requests:
            cpu: 250m
            memory: 128Mi
        livenessProbe: 
          httpGet: 
            path: /
            port: 80
          failureThreshold: 3
          periodSeconds: 10
          successThreshold: 1
          timeoutSeconds: 1
        readinessProbe: 
          httpGet: 
            path: /
            port: 80
          failureThreshold: 3
          periodSeconds: 10
          successThreshold: 1
          timeoutSeconds: 1