apiVersion: v1
kind: Service
metadata:
  name: nginx-web
spec:
  selector:
    app: "nginx-web-app"
  ports:
  - protocol: TCP
    port: 80  # Port for service
    targetPort: 80  # Target container port