apiVersion: apps/v1
kind: Deployment
metadata:
  name: nginx-web
spec:
  selector:
    matchLabels:
      app: nginx-web-app
  replicas: 10 # Start with 10 pods and reduce to 2 pods and check is health.sh is ready
  template:
    metadata:
      labels:
        app: nginx-web-app
    spec:
      containers:
      - name: nginx
        image: nginx:1.23.3-alpine
        ports:
        - containerPort: 80
        resources:
          limits:
            cpu: 1000m 
            memory: 256Mi
          requests:
            cpu: 250m
            memory: 128Mi
        livenessProbe: 
          httpGet: 
            path: /
            port: 80
          failureThreshold: 3
          periodSeconds: 10
          successThreshold: 1
          timeoutSeconds: 1
        readinessProbe: 
          httpGet: 
            path: /
            port: 80
          failureThreshold: 3
          periodSeconds: 10
          successThreshold: 1
          timeoutSeconds: 1